site_name: "" 

nav:
  - Home: index.md
  - Contribute:
    -  contribute.md
  - Community:
    -  community.md  
  - Tags: 
    - tags.md
      
theme:
  name: material 
  features:
    - navigation.tabs
    - navigation.sections

plugins:
  - search:
      lang: en
  - tags:
      tags_file: tags.md

